# Site settings
author: Damian
title: I Got This
header-img: img/home-bg.png
email: damian.malysza@gmail.com
copyright_name: Damian
description: > # this means to ignore newlines until "baseurl:"
  Even If I Think I Don't
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  damianmalysza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
